### ISSUE TITLE
Matto4 supports?

### ISSUE THREAD

**Issue by ni1chigo2115** [fholger/farcry_vrmod#22]
https://www.moddb.com/mods/matto4
I like matto4, is it possible to make it compatible?
As I said, I don't think a two gun SMG would work...

**Comment by fholger** [comment]
I don't know. It doesn't ship its own CryGame.dll, which is good. But it does overwrite some of the same scripts (specifically weapons) that the VR mod does, so the scripts would need to be merged; or you could try to see what happens if you use the VR versions of the scripts. It definitely won't work with the Matto4 versions.

**Comment by benjamincheng10** [comment]
oh man this would be awesome!

**Comment by VladimirDivak** [comment]
Any modification is supported, however you will need to:

1. copy the files from **Far Cry > Mods > CryVR** to the folder with the target mod
2. make a copy of the `.bat` file and correct the line that adds the parameter to start the mod: `start /B /WAIT FarCry.exe "-MOD:*mod folder name in Far Cry Cry > Mods*"`.

I haven't figured out yet how to edit the scripts of new weapons so that they are compatible with VR, but in **Matto4** you can use weapons from the original more often.

**Comment by benjamincheng10** [comment]
I managed to get Matto2, Matto3, and Matto4 running!

1. install mods
2. copy all files from **CryVR** to desired mod folder
3. make a new batch file in main dir, `bin32\Farcry.exe -MOD:Matto4`
4. launch game from this batch file while SteamVR is running.
5. create a new profile for each mod so you can have independent save files.
6. start new game

notes: 
-VR options menu not available in mods, but you can change them in the main game and they will carry over in mods
-in Matto4, there is a screen effect that makes the game render incorrectly, turn "effects quality" to low and restart mod to fix.
-custom guns in Matto3 and Matto4 works, but are weird, sideways with arms attached. regular guns works just fine.
-works for many mods, same steps, just change -MOD:ModName to the name of the desired mod folder
